# Generated by Django 5.2.12 on 2026-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='best_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='booking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='budget_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_label',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='must_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='short',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
