# Generated by Django 5.2.12 on 2026-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='card_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='display_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='hotel_search',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='package_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='short',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='things_to_do',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
