# Generated by Django 5.2.12 on 2026-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lineup',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='price_display',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='short',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_display',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='what_to_pair',
            field=models.TextField(blank=True),
        ),
    ]
