# Generated by Django 5.2.12 on 2026-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='best_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='card_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='destination_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='gallery_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='tiers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
