# Generated by Django 5.2.12 on 2026-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_display',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
